
hippunfold_dir: /scratch/kferko/hippunfold_dev
prepdwi_dir: /scratch/kferko/prepdwi_v0.0.12d/prepdwi


singularity:
  ants: '/project/6050199/akhanf/singularity/ants-v2.3.1.sif'
  fsl: '/project/6050199/akhanf/singularity/bids-apps/fsl_6.0.3_cuda9.1.sif' 

